/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Mortgage;

import java.awt.Color;
import java.text.NumberFormat;

/**
 *
 * @author rdschlu0000
 */
public class MortgageCalc extends javax.swing.JFrame {

     /**
      * Creates new form MortgageCalc
      */
     
     //declare global variables
     private int valCount;
     private int term;
     private double principal;
     private double interest;
     private double additionalAmt;
     private double decimalInt;
     private double payment;
     private double monthlyInt;
     private double monthlyPrin;
     private double newPrincipal;
     private double lifeInt;
     private double lifeInt2;
     private double savings;
     private int i;
     private int timesavings;
     private int years;
     private int months;
     
     
     public MortgageCalc() {
          initComponents();
          jLabel19.setVisible(false);
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     
     // method that performs the mortgage amortization calculations
     // necessary for the interest data.
     private void amortizationCalc()
     {
          // Formatter used to format currency
          NumberFormat currencyFormatter = NumberFormat.getCurrencyInstance();
          lifeInt = 0;
          lifeInt2 = 0;
          i = 0;
          term = Integer.parseInt(jTextField3.getText());
          principal = Double.parseDouble(jTextField1.getText());
          interest = Double.parseDouble(jTextField4.getText());
          decimalInt = interest / 1200;
          // This equation determines the monthly payment amount
          payment = principal * (decimalInt / (1 - Math.pow((1 + decimalInt), -term)));
          
          // Iteration for amortization of loan
          while (principal > 0)
          {
               
               monthlyInt = principal * decimalInt;
               // Correctly calculates the last payment to the loan
               if (principal < payment)
               {
                    
                    payment = principal + monthlyInt;
                    
               }
               monthlyPrin = payment - monthlyInt;
               newPrincipal = principal - monthlyPrin;
               principal = newPrincipal;
               // Holds the running total for interest payments
               lifeInt = lifeInt + monthlyInt;
               
          }
          
          jTextField8.setText(String.valueOf(currencyFormatter.format(lifeInt)));
          
          if (!jTextField5.getText().equals(""))
          {
          term = Integer.parseInt(jTextField3.getText());     
          principal = Double.parseDouble(jTextField1.getText());
          interest = Double.parseDouble(jTextField4.getText());
          additionalAmt = Double.parseDouble(jTextField5.getText());
          // gets the monthly interest in decimal form
          decimalInt = interest / 1200;
          payment = principal * (decimalInt / (1 - Math.pow((1 + decimalInt), -term)));
          
          while (principal > 0)
          {
               
               monthlyInt = principal * decimalInt;
               if (principal < payment)
               {
                    
                    payment = principal + monthlyInt;
                    
               }
               monthlyPrin = payment + additionalAmt - monthlyInt;
               newPrincipal = principal - monthlyPrin;
               principal = newPrincipal;
               // Holds the running total for interest payments
               lifeInt2 = lifeInt2 + monthlyInt;
               // Counts the number of payments made
               i++;
               
          }
          
          timesavings = term - i;
          years = Math.round(timesavings / 12);
          months = timesavings - (years * 12);
          savings = lifeInt - lifeInt2;
          // Total interest paid
          jTextField7.setText(String.valueOf(currencyFormatter.format(lifeInt2)));
          // Total interest paid with additional principal payments
          jTextField9.setText(String.valueOf(currencyFormatter.format(savings)));
          // Month, year data for display
          jTextField10.setText(String.valueOf(years) + " year(s) " + String.valueOf(months) + " month(s)");
          
          }
     }
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel9 = new javax.swing.JLabel();
          jLabel1 = new javax.swing.JLabel();
          jLabel7 = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          jPanel3 = new javax.swing.JPanel();
          jLabel2 = new javax.swing.JLabel();
          jTextField1 = new javax.swing.JTextField();
          jLabel4 = new javax.swing.JLabel();
          jTextField3 = new javax.swing.JTextField();
          jLabel5 = new javax.swing.JLabel();
          jTextField4 = new javax.swing.JTextField();
          jButton1 = new javax.swing.JButton();
          jLabel11 = new javax.swing.JLabel();
          jTextField5 = new javax.swing.JTextField();
          jTextField8 = new javax.swing.JTextField();
          jLabel12 = new javax.swing.JLabel();
          jLabel13 = new javax.swing.JLabel();
          jTextField7 = new javax.swing.JTextField();
          jLabel19 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          jTextField9 = new javax.swing.JTextField();
          jLabel10 = new javax.swing.JLabel();
          jTextField10 = new javax.swing.JTextField();
          jButton2 = new javax.swing.JButton();

          jLabel9.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
          jLabel9.setText("Fill out the fields below to determine the potential savings!");

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setTitle("Mortgage Payoff Assistant");
          setName("MortgageSavingsCalculator"); // NOI18N
          setPreferredSize(new java.awt.Dimension(600, 640));
          setResizable(false);

          jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
          jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mortgage/home.png"))); // NOI18N
          jLabel1.setLabelFor(this);

          jLabel7.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
          jLabel7.setForeground(java.awt.Color.darkGray);
          jLabel7.setText("Mortgage Savings Calculator");

          jLabel8.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jLabel8.setForeground(java.awt.Color.darkGray);
          jLabel8.setText("Fill out the fields below to determine the potential savings!");

          jPanel3.setPreferredSize(new java.awt.Dimension(600, 450));

          jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jLabel2.setText("Original Principal");

          jTextField1.setBackground(java.awt.Color.darkGray);
          jTextField1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jTextField1.setForeground(java.awt.Color.white);
          jTextField1.setToolTipText("Original dollar amount of loan.  Please subtract the down payment");

          jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jLabel4.setText("Term (Months)");

          jTextField3.setBackground(java.awt.Color.darkGray);
          jTextField3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jTextField3.setForeground(java.awt.Color.white);
          jTextField3.setToolTipText("original loan term example: 30 years = 360 months");

          jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jLabel5.setText("Interest Rate");

          jTextField4.setBackground(java.awt.Color.darkGray);
          jTextField4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jTextField4.setForeground(java.awt.Color.white);
          jTextField4.setToolTipText("Your interest rate");

          jButton1.setText("Submit");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          jLabel11.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jLabel11.setText("Additional Principal");

          jTextField5.setBackground(java.awt.Color.darkGray);
          jTextField5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jTextField5.setForeground(new java.awt.Color(255, 255, 255));
          jTextField5.setToolTipText("The extra amount you would like to apply toward principal each month");

          jTextField8.setEditable(false);
          jTextField8.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jTextField8.setToolTipText("The extra amount you would like to apply toward principal");
          jTextField8.setFocusable(false);

          jLabel12.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jLabel12.setText("Total Interest Paid (Additional Principal Applied)");

          jLabel13.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jLabel13.setText("Total Interest Paid (No Additional Principal)");

          jTextField7.setEditable(false);
          jTextField7.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jTextField7.setToolTipText("The extra amount you would like to apply toward principal");
          jTextField7.setFocusable(false);

          jLabel19.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jLabel19.setForeground(java.awt.Color.red);
          jLabel19.setText("Some fields were completed incorrectly...");

          jLabel6.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jLabel6.setText("Savings");

          jTextField9.setEditable(false);
          jTextField9.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jTextField9.setToolTipText("The extra amount you would like to apply toward principal");
          jTextField9.setFocusable(false);

          jLabel10.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jLabel10.setText("Time Saved");

          jTextField10.setEditable(false);
          jTextField10.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
          jTextField10.setToolTipText("The extra amount you would like to apply toward principal");
          jTextField10.setFocusable(false);

          jButton2.setText("Clear");
          jButton2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
          jPanel3.setLayout(jPanel3Layout);
          jPanel3Layout.setHorizontalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel3Layout.createSequentialGroup()
                              .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                             .addComponent(jLabel11)
                                             .addComponent(jLabel5)
                                             .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                             .addComponent(jTextField5))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jLabel6)
                                             .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jLabel10)
                                             .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                         .addGroup(jPanel3Layout.createSequentialGroup()
                              .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                             .addComponent(jLabel2)
                                             .addComponent(jLabel4)
                                             .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                             .addComponent(jTextField1))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addComponent(jLabel13)
                                             .addComponent(jLabel12)
                                             .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   .addComponent(jLabel19))
                              .addGap(0, 88, Short.MAX_VALUE))))
          );
          jPanel3Layout.setVerticalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel2)
                         .addComponent(jLabel13))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(jLabel12))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel11)
                         .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jButton1)
                         .addComponent(jButton2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel19)
                    .addContainerGap(111, Short.MAX_VALUE))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel1)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel7)
                                   .addComponent(jLabel8))))
                    .addContainerGap(258, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(11, 11, 11))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addComponent(jLabel7)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel8)
                              .addGap(30, 30, 30)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(67, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
          //clears fields
          jTextField8.setText("");
          jTextField7.setText("");
          jTextField9.setText("");
          jTextField10.setText("");
          
          // counter used for validation tracking
          valCount = 5;
          
          // regex for validation of text fields
          String currencyRegex = "^?([0-9]{1,3}([0-9]{3})*[0-9]{3}|[0-9]+)(.[0-9][0-9])?$";
          
          String intRegex = "[0-9]+(\\.[0-9][0-9]?[0-9]?[0-9]?[0-9]?)?";
          
          String termRegex = "^[0-9]{2,3}$";
          
          jLabel2.setForeground(Color.BLACK);
          jLabel4.setForeground(Color.BLACK);
          jLabel5.setForeground(Color.BLACK);
          jLabel11.setForeground(Color.BLACK);
          
          if (!jTextField1.getText().matches(currencyRegex))
          {
              
              // If it doesnt match it will  clear the field, turn the label red,
              // turn the notification label to visible, and iterate valCount back by one
              jTextField1.setText("");
              jLabel2.setForeground(Color.RED);
              jLabel19.setVisible(true);
              valCount--;
              
          }
          
          if (!jTextField3.getText().matches(termRegex))
          {
               
              jTextField3.setText("");
              jLabel4.setForeground(Color.RED);
              jLabel19.setVisible(true);
              valCount--;
              
          }
          
          if (!jTextField4.getText().matches(intRegex))
          {
               
              jTextField4.setText("");
              jLabel5.setForeground(Color.RED);
              jLabel19.setVisible(true);
              valCount--;
              
          }
          
          if (!jTextField5.getText().matches(currencyRegex) && !jTextField5.getText().equals(""))
          {
               
              jTextField5.setText("");
              jLabel11.setForeground(Color.RED);
              jLabel19.setVisible(true);
              valCount--;
              
          }
          
          if (valCount == 5)
          {
               
              jLabel19.setVisible(false);
              
              amortizationCalc();
              
          }
               
     }//GEN-LAST:event_jButton1ActionPerformed

     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
          jLabel19.setVisible(false);
          jTextField5.setText("");
          jTextField4.setText("");
          jTextField3.setText("");
          jTextField1.setText("");
          jTextField7.setText("");
          jTextField8.setText("");
          jTextField9.setText("");
          jTextField10.setText("");
          jLabel11.setForeground(Color.BLACK);
          jLabel5.setForeground(Color.BLACK);
          jLabel4.setForeground(Color.BLACK);
          jLabel2.setForeground(Color.BLACK);
          
     }//GEN-LAST:event_jButton2ActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
           * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(MortgageCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(MortgageCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(MortgageCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(MortgageCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               public void run() {
                    new MortgageCalc().setVisible(true);
                    
               }
          });
     }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton2;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel11;
     private javax.swing.JLabel jLabel12;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel19;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JPanel jPanel3;
     private javax.swing.JTextField jTextField1;
     private javax.swing.JTextField jTextField10;
     private javax.swing.JTextField jTextField3;
     private javax.swing.JTextField jTextField4;
     private javax.swing.JTextField jTextField5;
     private javax.swing.JTextField jTextField7;
     private javax.swing.JTextField jTextField8;
     private javax.swing.JTextField jTextField9;
     // End of variables declaration//GEN-END:variables
}
